In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [2]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

/run/media/aadimprajapati/New Volume/fnclick/python/nlp/languagemodeling/env/lib/python3.12/site-packages/torchtext/data/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/run/media/aadimprajapati/New Volume/fnclick/python/nlp/languagemodeling/env/lib/python3.12/site-packages/torchtext/vocab/__init__.py:4: UserWarning: 
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\ 
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)
/run/media/aadimp

In [11]:
from sklearn.model_selection import train_test_split

In [3]:
with open('data/paragraphs.txt', 'r') as file:
    para = file.read()

In [4]:
paragraphs = [x for x in para.split('\n')]

In [12]:
xtrain, xtest = train_test_split(paragraphs, test_size=0.2, random_state=42)

In [5]:
tokenizer = get_tokenizer('basic_english')

def get_tokens(paragraphs):
    for x in paragraphs:
        yield tokenizer(x)

In [13]:
tokens = get_tokens(xtrain)

In [14]:
vocab = build_vocab_from_iterator(tokens, specials=['<unk>'])

In [15]:
vocab.set_default_index(vocab['<unk>'])

In [17]:
data = [torch.tensor(vocab(tokenizer(item)), dtype=torch.long) for item in xtrain]

In [18]:
data

[tensor([    1,  3358,  5964,     8,    46,    94,    26, 45652, 24204,    32,
         30428,   783,     2,   978,   112,     7, 64627,    38,     2,   408,
            42,    43,  3749,     8,  4947,     3]),
 tensor([    5,  6296,     2,   930,    15,    19,   748, 28464,     2,    44,
             9,     1,  1001,   245,     4,     1,   159,     6,    41, 61153,
          5457,     2,   695,    26,  3888,     4,     1,  1164,     4,  3615,
            15,    19, 61373,     4,  1367,  5604]),
 tensor([  27,   60,   56,    7,  950,  195,  115,    4,    1, 1765,   79,  583,
           59,    5,    1, 7401,   10,    7,   69,    3,   53,   37,   58,   68,
           14,   67,   21,    3]),
 tensor([  794,  2360,     8,  1970, 15817,    28,    11,  7346,  2124,    22,
             1,   301, 11032,   266,    22, 50566,   316,     6,     1,   301,
           480, 19310,   405,    22, 45629,   301,   480,   737,     3,   135,
         19160,   664,    29, 15817,     6,    29,  2291,   943, 