In [1]:
! pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/8b/09/4ffb4d6cfe7ca6707336187951992bd8a8b9142cf345d87ab858d2d7636a/numpy-2.2.5-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-2.2.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.5-cp312-cp312-win_amd64.whl (12.6 MB)



[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
! python -m pip install --upgrade pip

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/c9/bc/b7db44f5f39f9d0494071bddae6880eb645970366d0a200022a1a93d57f5/pip-25.0.1-py3-none-any.whl.metadata
  Using cached pip-25.0.1-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-25.0.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1


In [44]:
! pip install scipy

In [3]:
! pip install scikit-learn
! pip install matplotlib
! pip install pandas
! pip install nltk

  Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Using cached scipy-1.15.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl (11.1 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.15.2-cp312-cp312-win_amd64.whl (40.9 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------- -------------------------- 2.6/8.1 MB 15.1 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.1 MB 15.4 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 14.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 13.7 MB/s eta 0:00:00
   -------------------------------

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk

In [3]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to C:\Users\user/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nlt

True

In [4]:
dataset = pd.read_csv('data/tweets_dataset.csv')
dataset

name                                              tweet  \
0         Billie Eilish  i’m fine. just floating in a hoodie-shaped clo...   
1         Ryan Reynolds  I watched Frozen without my two-year-old this ...   
2         Billie Eilish  people really be like “you’ve changed” like th...   
3         Billie Eilish  people really be like “you’ve changed” like th...   
4             Elon Musk                                         Nuke Mars!   
..                  ...                                                ...   
115           Elon Musk                                         Nuke Mars!   
116        Taylor Swift  "It's crazy to think about how many countries ...   
117       Conan O'Brien  "Nothing is more frightening than a clown tell...   
118  Tyler, the Creator  dreamt i opened a jazz bakery and now i’m mad ...   
119       Billie Eilish  people really be like “you’ve changed” like th...   

     is_real  
0      False  
1       True  
2      False  
3      False  
4       True  
..       ...  
115     True  
116     True  
117     True  
118    False  
119    False  

[120 rows x 3 columns]

In [5]:
features = ['name', 'tweetcmt']

In [6]:
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [7]:
wnl = WordNetLemmatizer()
ps = PorterStemmer()

stopword = set(stopwords.words('english'))

In [8]:
import unicodedata
import re

In [9]:
def clean_text(text):
    # Normalize unicode characters (fix things like ’ to ’)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    return text

In [10]:
def preprocessed_text(text):
    text = clean_text(text) 
    text = text.lower()

    text = re.sub(r"http\S+|@\S+|#\S+", "", text)

    tokens = word_tokenize(text)

    filtered = [token for token in tokens if token not in stopword and re.match(r'^[a-zA-Z\-]+$', token)]

    lemmas = [wnl.lemmatize(x) for x in filtered]
    stemmed = [ps.stem(x) for x in lemmas]

    return ' '.join(stemmed)


In [11]:
dataset['tweetcmt'] = dataset['tweet'].apply(preprocessed_text)

In [12]:
dataset

name                                              tweet  \
0         Billie Eilish  i’m fine. just floating in a hoodie-shaped clo...   
1         Ryan Reynolds  I watched Frozen without my two-year-old this ...   
2         Billie Eilish  people really be like “you’ve changed” like th...   
3         Billie Eilish  people really be like “you’ve changed” like th...   
4             Elon Musk                                         Nuke Mars!   
..                  ...                                                ...   
115           Elon Musk                                         Nuke Mars!   
116        Taylor Swift  "It's crazy to think about how many countries ...   
117       Conan O'Brien  "Nothing is more frightening than a clown tell...   
118  Tyler, the Creator  dreamt i opened a jazz bakery and now i’m mad ...   
119       Billie Eilish  people really be like “you’ve changed” like th...   

     is_real                                           tweetcmt  
0      False    im fine float hoodie-shap cloud existenti dread  
1       True  watch frozen without two-year-old morn despair...  
2      False  peopl realli like youv chang like that whole p...  
3      False  peopl realli like youv chang like that whole p...  
4       True                                           nuke mar  
..       ...                                                ...  
115     True                                           nuke mar  
116     True             crazi think mani countri lost hair tie  
117     True          noth frighten clown tell need wear makeup  
118    False        dreamt open jazz bakeri im mad doesnt exist  
119    False  peopl realli like youv chang like that whole p...  

[120 rows x 4 columns]

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [14]:
from scipy.sparse import hstack
name_vectorizer = TfidfVectorizer()
tweet_vectorizer = TfidfVectorizer()

name_vect = name_vectorizer.fit_transform(dataset['name'])
tweet_vect = tweet_vectorizer.fit_transform(dataset['tweetcmt'])

X = hstack([name_vect, tweet_vect])

In [15]:
# X = dataset[features]
y = dataset['is_real']

In [16]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [17]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [18]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, random_state=42, test_size=0.2)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
model = LogisticRegression()
model.fit(xtrain, ytrain)

LogisticRegression()

In [21]:
ypred = model.predict(xtest)

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [23]:
accuracy_score(ytest, ypred)

0.875

In [24]:
confusion_matrix(ytest, ypred)

array([[ 9,  0],
       [ 3, 12]])

In [25]:
x_new_test = {
    'name' : 'Chris Evan',
    'tweet' : 'Just wrapped an amazing project. Can’t wait for you all to see it! 🚀 Grateful for this journey every single day. #NewBeginnings #Blessed'
}

In [35]:
x_new_test = {
    'name' : 'NASA',
    'tweet' : 'Happy 34th birthday to the Hubble Space Telescope! 🎉 Since 1990, Hubble has revolutionized our understanding of the universe, capturing breathtaking images of distant galaxies, nebulae, and beyond.'
}

In [36]:
x_new_test['tweetcmt'] = preprocessed_text(x_new_test['tweet'])
x_new_test['tweetcmt']

'happi birthday hubbl space telescop sinc hubbl revolution understand univers captur breathtak imag distant galaxi nebula beyond'

In [37]:
test_name_vect = name_vectorizer.transform([x_new_test['name']])
test_tweet_vect = tweet_vectorizer.transform([x_new_test['tweetcmt']])

In [38]:
xcustomtest = hstack([name_vect, tweet_vect])

In [42]:
ycustomtest = model.predict(xcustomtest[0])

In [41]:
ycustomtest

array([0])